### ISSUE TITLE
Question about h value

### ISSUE THREAD

**Issue by eric-tc** [zjfheart/Robust-ResNet#1]
Hi,
thanks for your work. I will to try on custom datasets. I have a question regarding the choice of h value. 

Do you think could be useful to have different value of h, due to proposition 1, at different residual layer? My concern is that in the last residual block the upper bound create a very strong constraint on the variations of the weights. While in the first residual block maybe could be beneficial to add a smaller value of h to reduce variations of weights. I would try to set h with different values. Have you already tried this option? If yes did you get better results?

**Comment by zjfheart** [comment]
> the last residual block the upper bound create a very strong constraint on the variations of the weights. While in the first residual block maybe could be beneficial to add a smaller value of h to reduce variations of weights.

Thanks for asking the question! 
Yes. You are right! We have plotted the weights and gradients over the training iterations of both original ResNet and robust ResNet. Figure 10 in the paper <https://arxiv.org/pdf/1902.10887.pdf> shows that the initial residual block has larger variations than the last residual blocks in terms of weight gradients.  Therefore, it is beneficial to have smaller h in initial blocks and larger h in the final blocks. 

> "Have you already tried this option?"  No, I didn't try this option. But, it is a promising future work.
